version: "3"
services:
  app:
    build:
      context: .
      target: app
    env_file: ".env"
    environment:
      - DATABASE_URL=postgres://x3_admin@database:5432/x3_counter
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=x3_admin
      - POSTGRES_DB=x3_counter
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./sql/init:/docker-entrypoint-initdb.d"
      - "/custom/psql/data:/var/lib/postgresql/data"
    healthcheck:
      test: "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 5s
      timeout: 10s
      retries: 5
